title: "[Briefing] "
labels: ["General Introduction"]
body:
- type: input
  id: suggestion
  attributes:
    label: Improvement Suggestion
    description: "Share your ideas or feedback that could enhance the project's quality, usability, or documentation."
    placeholder: "For example: Improve the README with setup instructions, or add API usage examples."
  validations:
    required: true